project:
  type: website

website:
  title: "Cartes échantillons Saguenay 2023"
  navbar:
    left:
      - href: index.qmd
        text: Endofaune Judith

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



